<a href="https://colab.research.google.com/github/Amoldwalunj/Customer-complaints-text-classification/blob/main/customer_complaints_classification_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import os
import datetime
import tensorflow_hub as hub
import numpy as np
    
import pandas as pd
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras .preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
STOPWORDS= set(stopwords.words('english'))

In [ ]:


df=pd.read_csv('https://github.com/Amoldwalunj/Customer-complaints-text-classification/blob/main/consumer_compliants.zip?raw=true', compression='zip', sep=',', quotechar='"')



In [ ]:
df

Date received  ... Complaint ID
0          4/3/2020  ...      3591341
1         3/12/2020  ...      3564184
2          2/6/2020  ...      3521949
3          3/6/2020  ...      3556237
4         2/14/2020  ...      3531704
...             ...  ...          ...
57448     2/29/2020  ...      3549178
57449     2/11/2020  ...      3527928
57450     2/29/2020  ...      3549238
57451     1/16/2020  ...      3498566
57452     1/16/2020  ...      3498524

[57453 rows x 18 columns]

In [ ]:

STOPWORDS= set(stopwords.words('english'))

df['Consumer complaint narrative']= df['Consumer complaint narrative'].apply(lambda x: ' '.join([word for word in x.split() if word not in (STOPWORDS)]))

len(df['Consumer complaint narrative'][0])

df['Product']= df['Product'].replace(' ', '',regex=True)
df['Product']



0              Vehicleloanorlease
1                  Debtcollection
2              Vehicleloanorlease
3        Checkingorsavingsaccount
4                  Debtcollection
                   ...           
57448                 Studentloan
57449              Debtcollection
57450              Debtcollection
57451    Checkingorsavingsaccount
57452              Debtcollection
Name: Product, Length: 57453, dtype: object

In [ ]:
df.columns

from sklearn.utils import class_weight
class_weights = list(class_weight.compute_class_weight('balanced',
                                             np.unique(df['Product']),
                                             df['Product']))

df['Product'].value_counts()

class_weights.sort()

class_weights

weights={}


for index, weight in enumerate(class_weights) :
    weights[index]=weight

weights

{0: 0.43980801028844385,
 1: 0.7258015614340938,
 2: 0.9771915501581794,
 3: 1.3673425674710837,
 4: 3.2459322033898306,
 5: 3.4998172514619883}

In [ ]:


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras .preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords




vocab_size= 10000
embedding_dim=64
max_length=200
trunc_type= 'post'
padding_type='post'
oov_tok='<OOV'


labels= df['Product'].tolist()
labels

complaints= df['Consumer complaint narrative'].tolist()
complaints


["This auto loan opened XX/XX/2020 XXXX, NC BB & T name. I NEVER North Carolina I NEVER resident. I filed dispute twice credit bureaus times BB & T claimed accurate loan. Which I aware today. I tried contact BB & T multiple times I never gotten live person. I n't drive I never owned car before. I knowledge account I checked XXXXXXXX XXXX noticed it. I've tried twice dispute it. Additionally I never received bills information account. This last resort trying remove fraudulent loan account.",
 'In XXXX 2019 I noticed debt {$620.00} credit believed mine I thought speedy cash bought one old debts sold XXXX XXXX XXXX XXXX. I contacted XXXX XXXX XXXX XXXX several attempts giving full name, nothing came system. I gave social rep said account popped DID NOT tell account someone elses name continued let make payment. The payment {$120.00}. Confirmation number-XXXX. After realizing account, I called back get money back inform mistake. I told needed mail FTC report dispute letter get money back. 

In [ ]:
Y = pd.get_dummies(labels).values

In [ ]:
Y.shape

(57453, 6)

In [ ]:

training_portion= 0.8

int(len(complaints)* training_portion)

train_size= int(len(complaints)* training_portion)

train_complaints= complaints[0: train_size]
train_labels= Y[0: train_size]

validation_complaints= complaints[train_size:]
validation_labels= Y[train_size:]



In [ ]:
vocab_size= 10000
embedding_dim=64
max_length=500
trunc_type= 'post'
padding_type='post'
oov_tok='<OOV'


tokenizer= Tokenizer(num_words= vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(train_complaints)

word_index= tokenizer.word_index
word_index

len(list(word_index.items()))

train_sequences = tokenizer.texts_to_sequences(train_complaints)

train_complaints[0]

train_padded= pad_sequences(train_sequences, maxlen= max_length, padding='post',
    truncating='post')

train_padded[920]


array([   3,  155,  157,  813,    8,   17, 1893,  321,  295, 2643,  843,
         49,    3,  155,  157,  813,   17,   24,   26,    3,   19,  148,
         31,  477,    3,   30, 1253,    3, 1754,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [ ]:
validation_sequences= tokenizer.texts_to_sequences(validation_complaints)
validation_padded= pad_sequences(validation_sequences, maxlen= max_length, padding='post',
    truncating='post')

In [ ]:
model= tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim)),
    #tf.keras.layers.Dropout(0.1)
    tf.keras.layers.Dense(embedding_dim, activation= 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(6, activation='softmax')
    
])

model.summary()

model.compile(loss= 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          640000    
_________________________________________________________________
bidirectional (Bidirectional (None, None, 128)         66048     
_________________________________________________________________
bidirectional_1 (Bidirection (None, None, 128)         98816     
_________________________________________________________________
bidirectional_2 (Bidirection (None, None, 128)         98816     
_________________________________________________________________
bidirectional_3 (Bidirection (None, None, 128)         98816     
_________________________________________________________________
bidirectional_4 (Bidirection (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 64)                8

In [ ]:
epochs=5
batch_size=64
history= model.fit(train_padded, train_labels,  epochs=epochs, batch_size=batch_size, class_weight=weights, validation_split=0.1, verbose= 2)

Epoch 1/5
647/647 - 144s - loss: 1.0164 - accuracy: 0.6760 - val_loss: 0.6288 - val_accuracy: 0.7679
Epoch 2/5
647/647 - 123s - loss: 0.5291 - accuracy: 0.8133 - val_loss: 0.4973 - val_accuracy: 0.8434
Epoch 3/5
647/647 - 124s - loss: 0.3858 - accuracy: 0.8813 - val_loss: 0.4231 - val_accuracy: 0.8727
Epoch 4/5
647/647 - 122s - loss: 0.3193 - accuracy: 0.9048 - val_loss: 0.4320 - val_accuracy: 0.8730
Epoch 5/5
647/647 - 122s - loss: 0.3141 - accuracy: 0.9079 - val_loss: 0.4277 - val_accuracy: 0.8760


**model is slightly overfitting but still validation accuracy is very good so moving forward with final model**

In [ ]:
results = model.evaluate(validation_padded, validation_labels , verbose=2)

print(results)

360/360 - 19s - loss: 0.4347 - accuracy: 0.8682
[0.4347393810749054, 0.8682447075843811]


In [ ]:
y_pred= model.predict(validation_padded)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
validation_labels.argmax(axis=1)

array([0, 5, 2, ..., 2, 0, 2])

In [ ]:
y_pred.argmax(axis=1)

array([0, 2, 2, ..., 2, 2, 2])

In [ ]:
classification= classification_report(validation_labels.argmax(axis=1), y_pred.argmax(axis=1))

In [ ]:
print(classification)

              precision    recall  f1-score   support

           0       0.89      0.71      0.79      1507
           1       0.82      0.87      0.84      2952
           2       0.88      0.91      0.90      3939
           3       0.95      0.93      0.94      2097
           4       0.82      0.86      0.84       459
           5       0.74      0.74      0.74       537

    accuracy                           0.87     11491
   macro avg       0.85      0.84      0.84     11491
weighted avg       0.87      0.87      0.87     11491

